# Travis CI (MIT License) configuration file
# @link https://travis-ci.org/

os: linux

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
  - 5.6
  - 7.0
  - nightly

jobs:
  fast_finish: true

  include:
    - php: '7.4'
      env: SNIFF=1
    - php: '5.4'
      dist: trusty
    - php: '5.3'
      dist: precise
    - php: '5.2'
      dist: precise

  allow_failures:
    - php: 'nightly'

before_script:
    # Speed up build time by disabling Xdebug when its not needed.
    - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

    # Install dependencies.
    - |
      if [[ "$SNIFF" == "1" ]]; then
        composer install --no-suggest --no-interaction
      fi

# Run test script commands.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
    # Search for PHP syntax errors.
    - find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

    # Check code for style and cross-version compatibility issues.
    - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs; fi
